-- ============================================================
-- AHM Platform — Data Pipeline Migrations (Sprint 1)
-- Run all migrations in order in the Supabase SQL Editor.
-- Each migration is idempotent — safe to re-run.
--
-- Order:
--   001 — ingestion_runs
--   002 — data_quality_flags
--   003 — daily_prices indexes + adjusted_close columns
--   004 — index_history
--   005 — macro_indicators + sector_macro_linkages + seeded linkages
--   006 — corporate_actions + ttm_dividend_yield view
--   007 — earnings_calendar
--   008 — daily_snapshots
--   009 — pgvector + intelligence_embeddings
--
-- If running individually, apply in the numbered order above.
-- This file is a reference index — run individual files in Supabase.
-- ============================================================

--   023 — conviction_scores + conviction_score_history
--   024 — ai_outputs + ai_prompt_templates
--   025 — ai_market_snapshots + ai_event_triggers + alerts
--   026 — ai_generation_jobs + ai_quality_checks
--   027 — seed ai_prompt_templates v1.0.0
--   028 — sector_macro_drivers table (Sprint 6 Week 4)
--   029 — seed sector_macro_drivers for all 7 sectors (Sprint 6 Week 4)

