// services/api/alerts.ts
//
// Service layer for the alerts table.
// Components must import from here — never call supabase directly.
//
// ARCHITECTURE
//   Alerts are generated by fn-generate-alert and published to the alerts table.
//   The dashboard shows active, non-expired alerts ordered by severity then time.
//   Per-company and per-sector views filter by reference_key.

import { supabase } from '@/lib/supabase';
import type { Alert, AlertSeverity } from '@/types';

// ---- Read -------------------------------------------------------------------

/**
 * Active alerts for the dashboard notification strip.
 * Excludes expired alerts (expires_at < now) and inactive ones.
 * Ordered by severity (critical first) then recency.
 */
export async function getActiveAlerts(limit = 20): Promise<Alert[]> {
  const { data, error } = await supabase
    .from('alerts')
    .select('*')
    .eq('is_active', true)
    .or('expires_at.is.null,expires_at.gt.' + new Date().toISOString())
    .order('severity', { ascending: true })   // 'critical' < 'high' alphabetically — use case below
    .order('triggered_at', { ascending: false })
    .limit(limit)
    .returns<Alert[]>();

  if (error) { console.error('[alerts] getActiveAlerts:', error.message); return []; }

  // Sort by severity weight then time (Supabase can't order by enum position natively)
  const SEVERITY_WEIGHT: Record<AlertSeverity, number> = {
    critical: 0, high: 1, medium: 2, low: 3,
  };

  return (data ?? []).sort((a, b) => {
    const ws = SEVERITY_WEIGHT[a.severity] - SEVERITY_WEIGHT[b.severity];
    if (ws !== 0) return ws;
    return new Date(b.triggered_at).getTime() - new Date(a.triggered_at).getTime();
  });
}

/**
 * All active alerts for a specific company symbol.
 * Used on /stocks/[symbol] to show company-specific alerts.
 */
export async function getAlertsBySymbol(symbol: string): Promise<Alert[]> {
  const { data, error } = await supabase
    .from('alerts')
    .select('*')
    .eq('reference_key', symbol.toUpperCase())
    .eq('is_active', true)
    .or('expires_at.is.null,expires_at.gt.' + new Date().toISOString())
    .order('triggered_at', { ascending: false })
    .limit(10)
    .returns<Alert[]>();

  if (error) { console.error('[alerts] getAlertsBySymbol:', error.message); return []; }
  return data ?? [];
}

/**
 * Active alerts for a sector — where reference_key = sector_slug.
 */
export async function getAlertsBySector(sectorSlug: string): Promise<Alert[]> {
  const { data, error } = await supabase
    .from('alerts')
    .select('*')
    .eq('reference_key', sectorSlug)
    .eq('is_active', true)
    .or('expires_at.is.null,expires_at.gt.' + new Date().toISOString())
    .order('triggered_at', { ascending: false })
    .limit(8)
    .returns<Alert[]>();

  if (error) { console.error('[alerts] getAlertsBySector:', error.message); return []; }
  return data ?? [];
}

/**
 * Count of unread active alerts — for badge indicators.
 */
export async function getUnreadAlertCount(): Promise<number> {
  const { count, error } = await supabase
    .from('alerts')
    .select('id', { count: 'exact', head: true })
    .eq('is_active', true)
    .eq('is_read', false)
    .or('expires_at.is.null,expires_at.gt.' + new Date().toISOString());

  if (error) { console.error('[alerts] getUnreadAlertCount:', error.message); return 0; }
  return count ?? 0;
}

// ---- Write ------------------------------------------------------------------

/**
 * Mark a single alert as read.
 * Called from client components after the user views an alert.
 */
export async function markAlertRead(alertId: string): Promise<void> {
  const { error } = await supabase
    .from('alerts')
    .update({ is_read: true })
    .eq('id', alertId);

  if (error) console.error('[alerts] markAlertRead:', error.message);
}

/**
 * Mark all active alerts for a reference_key as read.
 */
export async function markAllReadForKey(referenceKey: string): Promise<void> {
  const { error } = await supabase
    .from('alerts')
    .update({ is_read: true })
    .eq('reference_key', referenceKey)
    .eq('is_active', true);

  if (error) console.error('[alerts] markAllReadForKey:', error.message);
}
